# Generated by Django 4.0.2 on 2022-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_chead0_blogpost_chead1_blogpost_chead2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='by_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
