# Generated by Django 4.0.2 on 2022-02-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='prod_amounr',
        ),
    ]
