# Generated by Django 4.0.2 on 2022-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_amount_orders_prod_amounr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='prod_amounr',
        ),
    ]
